// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooesmqqtxpouilcnqnjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZXNtcXF0eHBvdWlsY25xbmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTkzNjEsImV4cCI6MjA3MzY3NTM2MX0.TTva2T8hxbKvEEZoCpuCVSRPVXa9NTPVb8b3exIi2nY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});